pipeline {
  agent any
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  stages {
    stage('Preparation') {
      steps{
        deleteDir()
        sh 'git clone git@github.com:opengeospatial/ets-wfs20.git .'
      }
    }
    stage('Test') {
      steps{
        sh 'mvn --version'
        sh 'mvn clean com.smartbear.soapui:soapui-maven-plugin:test -Dsoapui.wfs20.teamengine.endpoint=${teamengineEndpoint} -Dsoapui.wfs20.ets.version=${etsVersion} -Dsoapui.wfs20.iut=${iut} -Dsoapui.wfs20.tests.passed=${testsPassed} -Dsoapui.wfs20.tests.skipped=${testsSkipped} -Dsoapui.wfs20.tests.failed=${testsFailed}'
      }
    }
    stage('Results') {
      steps{
        junit 'TEST-*.xml'
      }
    }
  }
}